-- AlterTable
ALTER TABLE "Comandas" ALTER COLUMN "valor" DROP NOT NULL,
ALTER COLUMN "entrada" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "producao" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "saida" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Produtos" ALTER COLUMN "preco" DROP NOT NULL;
